spring:
  liquibase:
    change-log: ${SPRING_DATASOURCE_URL:classpath:db/db.changelog-master.yaml}
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:hsqldb:mem:clinic
    username: ${SPRING_DATASOURCE_USERNAME:SA}
    password: ${SPRING_DATASOURCE_PASSWORD}