spring:
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: jdbc:hsqldb:mem:clinic
    username: SA
