spring:
  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:hsqldb:mem:clinic}
    username: ${SPRING_DATASOURCE_USERNAME:SA}
    password: ${SPRING_DATASOURCE_PASSWORD}